package com.oa.bean;


//Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.stereotype.Component;

/**
* CalInfo .
* 
* @author Lingo
*/
//@Entity
//@Table(name = "CAL_INFO")
@Component
public class Car implements java.io.Serializable {
 private static final long serialVersionUID = 0L;

 /** null. */
 private Long id;

 /** null. */
 private String carName;
 /** null. */
 
 private Integer carStatus;
 
 private Integer carPeople;
 
 private String code;
 
 private String driverName;
 
 private String driverPhone;
 
 private Set<CarInfo> carInfos = new HashSet<CarInfo>(0);
 
 public Car() {
 }
 
 public Car(Long id,String carName,String code,Integer carPeople){
	 this.id=id;
	 this.carName=carName;
	 this.code=code;
	 this.carPeople=carPeople;
 }
public Long getId() {
	return id;
}

public void setId(Long id) {
	this.id = id;
}

public String getCarName() {
	return carName;
}

public void setCarName(String carName) {
	this.carName = carName;
}

public Integer getCarStatus() {
	return carStatus;
}

public void setCarStatus(Integer carStatus) {
	this.carStatus = carStatus;
}



public Integer getCarPeople() {
	return carPeople;
}

public void setCarPeople(Integer carPeople) {
	this.carPeople = carPeople;
}

public String getDriverName() {
	return driverName;
}

public void setDriverName(String driverName) {
	this.driverName = driverName;
}

public String getDriverPhone() {
	return driverPhone;
}

public void setDriverPhone(String driverPhone) {
	this.driverPhone = driverPhone;
}

public String getCode() {
	return code;
}

public void setCode(String code) {
	this.code = code;
}

public Set<CarInfo> getCarInfos() {
	return carInfos;
}

public void setCarInfos(Set<CarInfo> carInfos) {
	this.carInfos = carInfos;
}

}
