package com.oa.bean;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.stereotype.Component;

/**
 * DocInfo .
 * 
 * @author Lingo
 */
@Component
public class DocPrivateInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String path;

    /** null. */
    private String type;

    /** null. */
    private Date createTime;

    /** null. */
    private Long userId;
    
    
    private String userName;
    
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	

   

	public DocPrivateInfo() {
    }

    public DocPrivateInfo(String name, String path, String type, Date createTime,
            Long userId) {
        this.name = name;
        this.path = path;
        this.type = type;
        this.createTime = createTime;
        this.userId = userId;
    }

    /** @return null. */
 
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
 
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */

    public String getPath() {
        return this.path;
    }

    /**
     * @param path
     *            null.
     */
    public void setPath(String path) {
        this.path = path;
    }


 

    public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/** @return null. */

    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            null.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return null. */
   
    public Long getUserId() {
        return this.userId;
    }

    /**
     * @param userId
     *            null.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}
