package com.oa.bean;

// Generated by Hibernate Tools
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.stereotype.Component;

/**
 * MeetingInfo .
 * 
 * @author Lingo
 */
//@Entity
//@Table(name = "MEETING_INFO")
@Component
public class MeetingInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private MeetingRoom meetingRoom;
    
    //private String meetingRoomId;
  
	/** null. */
    private String name;

   
	/** null. */
    private Timestamp startTime;

    /** null. */
    private Timestamp endTime;

    private Timestamp infoCreateTime;
    /** null. */
    private Long userId;

    public MeetingInfo() {
    }

    public MeetingInfo(MeetingRoom meetingRoom, String name, Timestamp startTime,
    		Timestamp endTime, Long userId,Timestamp infoCreateTime) {
        this.meetingRoom = meetingRoom;
        this.name = name;
        this.startTime = startTime;
        this.endTime = endTime;
        this.userId = userId;
        this.infoCreateTime=infoCreateTime;
    }

    /** @return null. */
   // @Id
   // @GeneratedValue
   // @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

   

	public Timestamp getInfoCreateTime() {
		return infoCreateTime;
	}

	public void setInfoCreateTime(Timestamp infoCreateTime) {
		this.infoCreateTime = infoCreateTime;
	}

	/** @return null. */
   // @ManyToOne(fetch = FetchType.LAZY)
   // @JoinColumn(name = "MEETING_ROOM_ID")
    public MeetingRoom getMeetingRoom() {
        return this.meetingRoom;
    }

    /**
     * @param meetingRoom
     *            null.
     */
    public void setMeetingRoom(MeetingRoom meetingRoom) {
        this.meetingRoom = meetingRoom;
    }

    /** @return null. */
    //@Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

  

    public Timestamp getStartTime() {
		return startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	/**
     * @param endTime
     *            null.
     */
    
    /** @return null. */
    //@Column(name = "USER_ID")
    public Long getUserId() {
        return this.userId;
    }

    public Timestamp getEndTime() {
		return endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	/**
     * @param userId
     *            null.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}
