package com.oa.bean;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * MeetingRoom .
 * 
 * @author Lingo
 */
//@Entity
//@Table(name = "MEETING_ROOM")
@Component
public class MeetingRoomBak implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private Integer people;

    private Integer state;
    
    private String roomAddress;
    
    private Date roomCreateTime;
    /** . */
    private Set<MeetingInfoBak> meetingInfoBaks = new HashSet<MeetingInfoBak>(0);

    public MeetingRoomBak() {
    }

    public MeetingRoomBak(String name, Integer people,
            Set<MeetingInfoBak> meetingInfoBaks,Integer state,String roomAddress) {
        this.name = name;
        this.people = people;
        this.meetingInfoBaks =meetingInfoBaks;
        this.state=state;
        this.roomAddress=roomAddress;
    }

    /** @return null. */
    //@Id
   // @GeneratedValue
    //@Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Date getRoomCreateTime() {
		return roomCreateTime;
	}

	public void setRoomCreateTime(Date roomCreateTime) {
		this.roomCreateTime = roomCreateTime;
	}

	/** @return null. */
   // @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    //@Column(name = "PEOPLE")
    public Integer getPeople() {
        return this.people;
    }

    /**
     * @param people
     *            null.
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

	public Set<MeetingInfoBak> getMeetingInfoBaks() {
		return meetingInfoBaks;
	}

	public void setMeetingInfoBaks(Set<MeetingInfoBak> meetingInfoBaks) {
		this.meetingInfoBaks = meetingInfoBaks;
	}

	public String getRoomAddress() {
		return roomAddress;
	}

	public void setRoomAddress(String roomAddress) {
		this.roomAddress = roomAddress;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

    /** @return . */
 
}
